services: docker

language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: test
      script:
        - npm test
        - npm run coverage
    - stage: deploy
      script:
        - npm run deploy

stages:
  - test
  - name: deploy
    if: branch = master
